### ISSUE TITLE
express use missing err

### ISSUE THREAD

**Issue by treyduffy** [williamcotton/browser-express#2]
I added this module with webpack (had to specify window && window.document in browserExpress({}) because it found them undefined inside webpack).

After running I tracked the lack of error handling to app.use. Your middleware assumes req/res/next without accounting for err/req/res/next which means there's no potential for trapping errors without rewriting server side code to match.

The goal was using the same validation middleware for the client and server.

**Comment by williamcotton** [comment]
@treyduffy Hey dude, I know it's been a few years, but I finally got around to rewriting this to use `router` from the `express` so it should now have much better compatibility including the requested `err` callback functionality!
